@startuml
class animation.grandma.DownWalk {
+ <<Create>> DownWalk()
}

class main.Main {
+ {static} Player player1
+ {static} Player player2
+ {static} boolean editMode
+ {static} GameTime gameTime
+ void start(Stage)
+ {static} void main(String[])
+ void stop()
}


class gui.ControlGrid {
+ <<Create>> ControlGrid()
- GridPane createPlayerControls(String,String,String,String,String,String)
- Circle addKeyWithCircleBackground(GridPane,String,int,int)
- Text createKeyText(String)
}

abstract class player.Player {
- int max_health
- int health
~ PlayerAnimation playerAnimation
- double playerSpeed
- double jumpPower
- double knockback
- double attack
+ <<Create>> Player(PlayerType,int,int,double,double,double)
+ double getPlayerSpeed()
+ void setPlayerSpeed(double)
+ int getHealth()
+ void setHealth(int)
+ PlayerAnimation getPlayerAnimation()
+ void setPlayerAnimation(PlayerAnimation)
+ int getMax_health()
+ void setMax_health(int)
+ {abstract}void initAnimation()
+ {abstract}void setDefault()
+ double getJumpPower()
+ void setJumpPower(double)
+ double getKnockback()
+ void setKnockback(double)
+ double getAttack()
+ void setAttack(double)
}


class type.constant.Settings {
+ {static} int DEFAULT_SCENE_WIDTH
+ {static} int DEFAULT_SCENE_HEIGHT
+ {static} int DEFAULT_BG_WIDTH
+ {static} int DEFAULT_BG_HEIGHT
+ {static} int GROUND_HEIGHT
}

class animation.grandda.RightWalk {
+ <<Create>> RightWalk()
}

class player.GrandMa {
+ {static} int MAX_HEALTH
+ {static} double SPEED
+ {static} double ATTACK
+ {static} double JUMP_POWER
+ {static} double KNOCKBACK
+ {static} int ANIMANTION_DELAY
+ <<Create>> GrandMa()
+ void move(KeyCode)
+ void attack(KeyCode)
+ void jump(KeyCode)
+ void stop(KeyCode)
+ void initAnimation()
+ void setDefault()
}


class animation.grandma.UpStay {
+ <<Create>> UpStay()
}

class system.AudioManager {
- Hashtable<String,Media> audioData
- MediaPlayer loopPlayer
- {static} AudioManager instance
- <<Create>> AudioManager()
+ {static} AudioManager getInstance()
+ void loadAudio()
+ void addAudio(String,String)
+ Media getAudio(String)
+ void playSingle(String)
+ void playLoop(String)
+ void stopLoop()
}


enum type.PlayerDirection {
+  UP
+  DOWN
+  RIGHT
+  LEFT
}

class system.SceneManager {
- {static} Stage mainStage
- {static} GameScene currentScene
- {static} Thread gameThread
+ {static} void setStage(Stage)
+ {static} void moveScene(GameScene)
+ {static} void startSceneScript(SceneLogic)
+ {static} void addPlayerToScene(Pane,int,int,int,int)
+ {static} GameScene getScene()
}


class gui.Room {
- String URL
- {static} int DEFAULT_SIZE
+ <<Create>> Room()
+ void setDimensions(double,double)
+ void setBackgroundImage(String)
}


class gui.HealthBar {
+ <<Create>> HealthBar(int,int,int)
}

enum type.GameTime {
+  NightTime
+  DayLight
}

class animation.grandda.LeftStay {
+ <<Create>> LeftStay()
}

class animation.AnimationList {
- AnimationNode head
- AnimationNode tail
- int duration
- AnimationNode current
+ <<Create>> AnimationList()
+ {static} AnimationList fromAnimationData(AnimationData)
+ boolean isEmpty()
+ void addFrame(String,double,double,double,double)
+ void addAnimation(AnimationData)
+ void resetNode()
+ AnimationNode getNextAnimation()
+ int getDuration()
+ void setDuration(int)
+ AnimationNode getCurrent()
}


enum type.PlayerType {
+  GrandMa
+  GrandDa
}

class animation.AnimationNode {
- ImageView imageView
- AnimationNode next
+ <<Create>> AnimationNode(String,double,double,double,double)
+ ImageView getImageView()
+ void setImageView(ImageView)
+ AnimationNode getNext()
+ void setNext(AnimationNode)
}


class animation.grandda.UpStay {
+ <<Create>> UpStay()
}

class scenes.fightscene.FightScene {
- HealthBar healthBar1
- HealthBar healthBar2
- {static} String[] BACKGROUND_NIGHT_TIME_IMAGES
- {static} String[] BACKGROUND_DAY_TIME_IMAGES
+ <<Create>> FightScene()
+ void initscene()
- void setBackground()
- String getRandomImagePath()
- void initChangeBGButton()
- void initChangeSceneButton()
+ void inithealthBars()
+ void setPlayerListener()
+ void endedScene()
- void initBackButton()
}


class animation.grandda.LeftAttack {
+ <<Create>> LeftAttack()
}

class animation.grandda.LeftWalk {
+ <<Create>> LeftWalk()
}

class animation.grandda.RightAttack {
+ <<Create>> RightAttack()
}

class scenes.roomscene.RoomScene {
- {static} double scaleFactor
- {static} int ACTUAL_ROOM_SIZE
- {static} double ROOM_SIZE
+ <<Create>> RoomScene()
+ void initscene()
- void setBackground()
- void initRooms()
- void initControlGrid()
- Room createRoom()
- void initEditButton()
+ void setPlayerListener()
}


class gui.PlayerModel {
- double moveDistanceX
- double moveDistanceY
- boolean isMovingUp
- boolean isMovingDown
- boolean isMovingLeft
- boolean isMovingRight
- boolean isRightAttacking
- boolean isLeftAttacking
- boolean isOnGround
- boolean isJump
- double initialSpeed
- boolean attackRight
- boolean attackLeft
- double forcePX
- double forceNX
- boolean isShow
+ <<Create>> PlayerModel(ImageView)
+ void setDimensions(double,double)
+ void setModel(ImageView)
+ void clearModel()
+ void setDefault()
+ double getX()
+ void setX(double)
+ double getY()
+ void setY(double)
+ void setLocation(double,double)
+ double getMoveDistanceX()
+ void setMoveDistanceX(double)
+ double getMoveDistanceY()
+ void setMoveDistanceY(double)
+ boolean isMovingUp()
+ void setMovingUp(boolean)
+ boolean isMovingDown()
+ void setMovingDown(boolean)
+ boolean isMovingLeft()
+ void setMovingLeft(boolean)
+ boolean isMovingRight()
+ void setMovingRight(boolean)
+ boolean isRightAttacking()
+ void setRightAttacking(boolean)
+ boolean isLeftAttacking()
+ void setLeftAttacking(boolean)
+ boolean isOnGround()
+ void setOnGround(boolean)
+ boolean isJump()
+ void setJump(boolean)
+ double getInitialSpeed()
+ void setInitialSpeed(double)
+ void decreaseSpeed(double)
+ boolean isAttackRight()
+ void setAttackRight(boolean)
+ boolean isAttackLeft()
+ void setAttackLeft(boolean)
+ double getForcePX()
+ void setForcePX(double)
+ double getForceNX()
+ void setForceNX(double)
+ boolean isShow()
+ void setShow(boolean)
}


class animation.EditFleid {
+ <<Create>> EditFleid()
- void createEditGrandMaGrid()
- void createEditGrandDaGrid()
- void removeEditGrid()
}

class animation.grandma.LeftWalk {
+ <<Create>> LeftWalk()
}

interface type.interfaces.Moveable {
+ void move(KeyCode)
+ void stop(KeyCode)
+ void attack(KeyCode)
+ void jump(KeyCode)
}

class animation.PlayerAnimation {
- PlayerType playerType
- PlayerDirection playerDirection
- PlayerModel model
- double hitblock
- Map<PlayerAction,AnimationList> animationMap
- Thread animantionThread
- int attackCount
- int animantionCount
- int animantionDelay
+ <<Create>> PlayerAnimation(PlayerType)
+ void initModel(ImageView)
+ void initAnimantionThread()
+ void changeAnimantion()
+ void setAnimation(PlayerAction)
+ void addPlayerAnimation(String[])
+ void addPlayerAnimation(PlayerAction,AnimationList)
+ PlayerType getPlayerType()
+ void setPlayerType(PlayerType)
+ PlayerDirection getPlayerDirection()
+ void setPlayerDirection(PlayerDirection)
+ PlayerModel getModel()
+ void setModel(PlayerModel)
+ Map<PlayerAction,AnimationList> getAnimationMap()
+ Thread getAnimantionThread()
+ int getAnimantionCount()
+ void setAnimantionCount(int)
+ double getHitblock()
+ void setHitblock(double)
+ int getAnimantionDelay()
+ void setAnimantionDelay(int)
}


abstract class system.GameScene {
- SceneLogic script
+ <<Create>> GameScene(SceneLogic)
+ SceneLogic getScript()
+ void setScript(SceneLogic)
+ {abstract}void initscene()
+ {abstract}void setPlayerListener()
}


class scenes.roomscene.RoomLogic {
+ void update()
- void movePlayer(Player)
- void checkSleep()
- void checkgameStart()
- boolean canPlayerMove(Player,PlayerDirection,double)
}

class animation.grandma.RightAttack {
+ <<Create>> RightAttack()
}

class gui.GameIcon {
+ {static} ImageView startButton(double)
+ {static} ImageView parseButton(double)
+ {static} ImageView stopButton(double)
+ {static} ImageView gameoverIcon(double,double)
+ {static} ImageView newgameIcon(double)
+ {static} ImageView fullHeart(int)
+ {static} ImageView halfHeart(int)
+ {static} ImageView emptyHeart(int)
+ {static} ImageView redPotion(double)
+ {static} ImageView bluePotion(double)
+ {static} ImageView yellowPotion(double)
}

class animation.grandma.DownStay {
+ <<Create>> DownStay()
}

class scenes.fightscene.FightLogic {
- FightScene view
+ void setView(FightScene)
+ void update()
- void movePlayer(Player)
- boolean canPlayerMove(Player,PlayerDirection,double)
- void attackPlayer(Player,Player)
}


class player.GrandDa {
+ {static} int MAX_HEALTH
+ {static} double SPEED
+ {static} double ATTACK
+ {static} double JUMP_POWER
+ {static} double KNOCKBACK
+ {static} int ANIMANTION_DELAY
+ <<Create>> GrandDa()
+ void move(KeyCode)
+ void jump(KeyCode)
+ void attack(KeyCode)
+ void stop(KeyCode)
+ void initAnimation()
+ void setDefault()
}


class animation.grandma.LeftStay {
+ <<Create>> LeftStay()
}

abstract class animation.AnimationData {
+ String[] frames
+ int width
+ int height
+ int offsetX
+ int offsetY
+ PlayerAction actionType
+ <<Create>> AnimationData(String[],int,int,int,int,PlayerAction)
}


class animation.grandda.DownWalk {
+ <<Create>> DownWalk()
}

class animation.grandma.RightStay {
+ <<Create>> RightStay()
}

class animation.grandda.UpWalk {
+ <<Create>> UpWalk()
}

class animation.grandda.DownStay {
+ <<Create>> DownStay()
}

interface type.interfaces.SceneLogic {
~ void update()
}

class animation.grandda.RightStay {
+ <<Create>> RightStay()
}

enum type.PlayerAction {
+  UP_STAY
+  UP_WALK
+  DOWN_STAY
+  DOWN_WALK
+  RIGHT_STAY
+  RIGHT_WALK
+  LEFT_STAY
+  LEFT_WALK
+  RIGHT_ATTACK
+  LEFT_ATTACK
}

class animation.grandma.RightWalk {
+ <<Create>> RightWalk()
}

class animation.grandma.UpWalk {
+ <<Create>> UpWalk()
}

class animation.grandma.LeftAttack {
+ <<Create>> LeftAttack()
}



animation.AnimationData <|-- animation.grandma.DownWalk
javafx.application.Application <|-- main.Main
javafx.scene.layout.Pane <|-- gui.ControlGrid
type.interfaces.Moveable <|.. player.Player
animation.AnimationData <|-- animation.grandda.RightWalk
player.Player <|-- player.GrandMa
animation.AnimationData <|-- animation.grandma.UpStay
javafx.scene.layout.Pane <|-- gui.Room
javafx.scene.layout.HBox <|-- gui.HealthBar
animation.AnimationData <|-- animation.grandda.LeftStay
animation.AnimationData <|-- animation.grandda.UpStay
system.GameScene <|-- scenes.fightscene.FightScene
animation.AnimationData <|-- animation.grandda.LeftAttack
animation.AnimationData <|-- animation.grandda.LeftWalk
animation.AnimationData <|-- animation.grandda.RightAttack
system.GameScene <|-- scenes.roomscene.RoomScene
javafx.scene.layout.Pane <|-- gui.PlayerModel
javafx.scene.layout.Pane <|-- animation.EditFleid
animation.AnimationData <|-- animation.grandma.LeftWalk
javafx.scene.layout.Pane <|-- system.GameScene
type.interfaces.SceneLogic <|.. scenes.roomscene.RoomLogic
animation.AnimationData <|-- animation.grandma.RightAttack
animation.AnimationData <|-- animation.grandma.DownStay
type.interfaces.SceneLogic <|.. scenes.fightscene.FightLogic
player.Player <|-- player.GrandDa
animation.AnimationData <|-- animation.grandma.LeftStay
animation.AnimationData <|-- animation.grandda.DownWalk
animation.AnimationData <|-- animation.grandma.RightStay
animation.AnimationData <|-- animation.grandda.UpWalk
animation.AnimationData <|-- animation.grandda.DownStay
animation.AnimationData <|-- animation.grandda.RightStay
animation.AnimationData <|-- animation.grandma.RightWalk
animation.AnimationData <|-- animation.grandma.UpWalk
animation.AnimationData <|-- animation.grandma.LeftAttack
@enduml